// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnxqhuyjokqtrjvjcfvx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxueHFodXlqb2txdHJqdmpjZnZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMjA3MDQsImV4cCI6MjA2NTU5NjcwNH0.8uDXPR-wnD6_hsZkjcM9nTm7cK67E19PAu9u_0lhZEE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);